---
- name: Install Python
  apt:
    name: python

    
- name: Instal MySQL
  include: mysql.yaml


- name: Create bd
  include: create_db.yaml

- name: Install Apache end php
  include: apache_install.yaml

- name: Install Drupal
  include: drupal.yaml
